
try {
    timeout(time: 15, unit: 'MINUTES') {
        node() {
           
            stage('Backend Deployment') {
                git(url:"${DEVOPS_CODEBASE_GIT_REPO}",
                branch:"${BRANCH_NAME}",
                credentialsId:'ritac041-in-health-planner-github-repo-access-secret')

                openshift.withCluster() {
                    openshift.withProject() {   

                        // create deployment resources
                        openshift.apply(openshift.process(  "-f", 
                                                            "./backend/deployment/backend-deployment-template.yaml"))

                        def deployment = openshift.selector("dc/healthplanner-backend")
                        deployment.rollout().status() //follow progress
                    }
                }
            }
        }
    }
	
} catch (err) {
    echo "in catch block"
    echo "Caught: ${err}"
    currentBuild.result = 'FAILURE'
    throw err
}
