apiVersion: v1
kind: Template
labels:
  template: health-planner-backend-deployment-template
message: Defines application deployment components
metadata:
  annotations:
    openshift.io/display-name: Deployment config
    description: Define the resources to deploy the application 
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: health-planner-backend-deployment-template

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: healthplanner-backend
    name: healthplanner-backend
  spec:
    replicas: 1
    selector:
      app: healthplanner-backend
    template:
      metadata:
        labels:
          app: healthplanner-backend
      spec:
        containers:
          - image: healthplanner-backend:latest
            name: healthplanner-backend
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 300m
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 250Mi
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - healthplanner-backend
          from:
            kind: ImageStreamTag
            name: 'healthplanner-backend:latest'
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: healthplanner-backend
    name: healthplanner-backend
  spec:
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: healthplanner-backend
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: healthplanner-backend
    name: healthplanner-backend
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
  spec:
    to:
      kind: Service
      name: healthplanner-backend
      weight: 100
    tls:
      termination: edge
    wildcardPolicy: None
